# LinearRegression benchmark (d=11) - Adaptive MCMC
model = linear.bngl : linear.exp
output_dir = output_am/
objfunc = sos
fit_type = am

uniform_var = W1__FREE -10 10
uniform_var = W2__FREE -10 10
uniform_var = W3__FREE -10 10
uniform_var = W4__FREE -10 10
uniform_var = W5__FREE -10 10
uniform_var = W6__FREE -10 10
uniform_var = W7__FREE -10 10
uniform_var = W8__FREE -10 10
uniform_var = W9__FREE -10 10
uniform_var = W0__FREE -10 10
uniform_var = b__FREE -10 10

population_size = 20
parallel_count = 20
max_iterations = 100000
burn_in = 50000
sample_every = 10
output_hist_every = 100
hist_bins = 50
step_size = 0.01
adaptive = 20000
rhat_threshold = 0
verbosity = 2
delete_old_files = 1
