# COVID19_BigApple benchmark (d=10) - P-DREAM
model = m1.bngl : m1.exp
output_dir = output_p_dream/
objfunc = neg_bin_dynamic
fit_type = p_dream

uniform_var = t0__FREE 0 60
uniform_var = t_delta__FREE 0 60
uniform_var = t_delta2__FREE 0 200
uniform_var = beta__FREE 0.0 10.0
uniform_var = lambda0__FREE 0.0 10.0
uniform_var = p0__FREE 0.0 1.0
uniform_var = lambda1__FREE 0.0 10.0
uniform_var = p1__FREE 0.0 1.0
uniform_var = fD__FREE 0.0 1.0
uniform_var = r__FREE 0.0 30.0

population_size = 20
parallel_count = 20
max_iterations = 100000
burn_in = 50000
sample_every = 10
output_hist_every = 100
hist_bins = 50
output_noise_trajectory = fDCs_Cum
rhat_threshold = 0
verbosity = 2
delete_old_files = 1
