# Banana (Rosenbrock) benchmark - Adaptive MCMC
model = banana.target : target.exp
output_dir = output_am/
objfunc = direct_pass
fit_type = am

uniform_var = x1 -5 5
uniform_var = x2 -5 15

population_size = 10
max_iterations = 10000
burn_in = 3000
sample_every = 10
output_hist_every = 50
hist_bins = 50
step_size = 0.3
adaptive = 1000
rhat_threshold = 1.05
verbosity = 2
delete_old_files = 1
wall_time_sim = 0
