# Multimodal mixture benchmark - S-CREAM
model = multimodal.target : target.exp
output_dir = output_scream/
objfunc = direct_pass
fit_type = s_cream

uniform_var = x1 -10 10
uniform_var = x2 -10 10

population_size = 20
max_iterations = 7000
burn_in = 5000
sample_every = 10
output_hist_every = 50
hist_bins = 50
snooker_prob = 0.2
verbosity = 2
delete_old_files = 1
wall_time_sim = 0
